import os
import sys
import time
from clint.textui import colored

print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print ('********************************************************************************')
print ('*                                                                              *')
print ('*                                                                              *')
print ('*                                                                              *')
print ('*                          ' + colored.white('Chill RPG Character ') + colored.red('Manager') + '                         *')
print ('*                                                                              *')
print ('*                                 Version 0.6                                  *')
print ('*                                                                              *')
print ('*                                                                              *')
print ('*                                                                              *')
print ("*                                                                              *")
print ('********************************************************************************')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
time.sleep(2)
chillrpg = "."
direc = (os.listdir(chillrpg))
print (direc)

char = input("Character Name: ")
char2 = "." + char + ".txt"
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')

charfile = open(char2)
selected_char = charfile.read()
print (selected_char)
time.sleep(2)

print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print ('#################### --' + char + '-- ####################')
print ('********************************************************************************')
print ('*                                                                              *')
print ('*                          Please choose an option                             *')
print ('*------------------------------------------------------------------------------*')
print ("*                                                                              *")
print ('*      1.) Delete Character                                                    *')
print ('*                                                                              *')
print ('*                                                                              *')
print ('*                                                                              *')
print ('*                                                                              *')
print ("*                                                                              *")
print ('********************************************************************************')
print (' ')
print (' ')
print (' ')
print (' ')
print (' ')
print ('Please make a selection. ')
select = input(':')

if select == "1":
    os.remove(char2)
    print(colored.red("CHARACTER ") + colored.blue(char) + colored.red(' HAS BEEN DELETED') )
    time.sleep(3)
    os.execl(sys.executable, sys.executable, *sys.argv)

